-- XÓA BẢNG CŨ --
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS blogs;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS destinations;
DROP TABLE IF EXISTS tours;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS users;

-- CẤU HÌNH H2 ---
CREATE DOMAIN IF NOT EXISTS "uuid" AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS "role_type" AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS "money" AS DECIMAL(10,2);

-- TẠO BẢNG MỚI ---

CREATE TABLE users (
    user_id VARCHAR(255) DEFAULT random_uuid() PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    role VARCHAR(50) DEFAULT 'user',
    country_id BIGINT,
    profile_image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE countries (
    country_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE cities (
    city_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    country_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES countries(country_id)
);

CREATE TABLE tours (
    tour_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    images VARCHAR ARRAY,
    duration BIGINT,
    rating DOUBLE,
    price VARCHAR(50),
    country_name VARCHAR(100)
);

CREATE TABLE destinations (
    destination_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT,
    tour_id BIGINT,
    FOREIGN KEY (city_id) REFERENCES cities(city_id),
    FOREIGN KEY (tour_id) REFERENCES tours(tour_id)
);

CREATE TABLE bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    tour_id BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    price DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (tour_id) REFERENCES tours(tour_id)
);

CREATE TABLE blogs (
    blog_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    content TEXT,
    images VARCHAR ARRAY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT,
    content TEXT,
    rating DOUBLE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)
);

CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    blog_id BIGINT,
    review_id BIGINT,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (blog_id) REFERENCES blogs(blog_id),
    FOREIGN KEY (review_id) REFERENCES reviews(review_id)
);