-- Định nghĩa các domain tương ứng với kiểu dữ liệu trong PostgreSQL
CREATE DOMAIN IF NOT EXISTS "uuid" AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS "role_type" AS VARCHAR(50);
-- Cấu trúc bảng Users (giả lập PostgreSQL)
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id VARCHAR(255) DEFAULT random_uuid() PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    role VARCHAR(50),
    country_id BIGINT,
    profile_image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Giả lập các kiểu dữ liệu đặc thù của Postgres
CREATE DOMAIN IF NOT EXISTS "uuid" AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS "role_type" AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS "money" AS DECIMAL(10,2);

-- Bảng Users
CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(255) DEFAULT random_uuid() PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    role VARCHAR(50),
    country_id BIGINT,
    profile_image VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bảng Tours
CREATE TABLE IF NOT EXISTS tours (
    tour_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    images TEXT, 
    duration BIGINT,
    rating DOUBLE,
    price VARCHAR(50),
    country_name VARCHAR(100)
);

-- Bảng Bookings
CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    tour_id BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    price DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (tour_id) REFERENCES tours(tour_id)
);

-- Bảng Countries
CREATE TABLE IF NOT EXISTS countries (
    country_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

-- Bảng Cities
CREATE TABLE IF NOT EXISTS cities (
    city_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    country_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES countries(country_id)
);

-- Bảng Destinations
CREATE TABLE IF NOT EXISTS destinations (
    destination_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT,
    tour_id BIGINT,
    FOREIGN KEY (city_id) REFERENCES cities(city_id),
    FOREIGN KEY (tour_id) REFERENCES tours(tour_id)
);